name: Daily Commit

on:
  workflow_dispatch:
  schedule:
    # Runs every day at 08:00 UTC (1:30 PM IST)
    - cron: '0 8 * * *'

jobs:
  commit-time:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 21f3002792@ds.study.iitm.ac.in
        run: |
          echo "Daily run at $(date)" >> daily-log.txt

      - name: Commit and Push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add daily-log.txt
          git commit -m "Daily log update" || echo "No changes to commit"
          git push
